apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: lab8
type: Opaque
data:
  POSTGRES_USER: bGFiNXVzZXI=         # "lab5user" en base64
  POSTGRES_PASSWORD: bGFiNXBhc3M=     # "lab5pass" en base64

